cartpole1:
  env_id: CartPole-v1
  replay_memory_size: 100000
  mini_batch_size: 32
  epsilon_init: 1.0
  epsilon_decay: 0.9995
  epsilon_min: 0.05
  network_sync_rate: 10
  gamma: 0.99
  learning_rate: 0.0001
  stop_on_reward: 100000
  fc1_nodes: 10

flappybird:
  env_id: FlappyBird-v0
  learning_rate: 0.001
  gamma: 0.99
  network_sync_rate: 10
  replay_memory_size: 100000
  mini_batch_size: 32
  epsilon_init: 1.0
  epsilon_decay: 0.9995
  epsilon_min: 0.05
  stop_on_reward: 100000
  fc1_nodes: 512
  env_config:
    use_lidar: False
